name: flabby_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.22.0
  flame_bloc: ^1.12.4
  e: ^1.0.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  flutter_animate: ^4.5.2
  flutter_soloud: ^2.1.7
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/background/
    - assets/audio/


  fonts:
    - family: Chewy
      fonts:
        - asset: assets/fonts/Chewy-Regular.ttf

